package com.tangem.core.ui.test

object TestTags {
    const val STORIES_SCREEN = "STORIES_SCREEN_CONTAINER"
    const val STORIES_SCREEN_SCAN_BUTTON = "STORIES_SCREEN_SCAN_BUTTON"
    const val STORIES_SCREEN_ORDER_BUTTON = "STORIES_SCREEN_ORDER_BUTTON"

    const val MAIN_SCREEN = "WALLET_SCREEN_CONTAINER"
    const val MAIN_SCREEN_MORE_BUTTON = "MAIN_SCREEN_MORE_BUTTON"
    const val MAIN_SCREEN_TOP_BAR = "MAIN_SCREEN_TOP_BAR"

    const val DETAILS_SCREEN = "DETAILS_SCREEN_CONTAINER"
    const val DETAILS_SCREEN_ITEM = "DETAILS_SCREEN_ITEM"
    const val DETAILS_SCREEN_SOCIAL_NETWORK_BUTTONS = "DETAILS_SCREEN_SOCIAL_NETWORK_BUTTONS"

}
